import {before,after,test} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {createTestDatabase} from '../scripts/lib/local-database.mjs';
import {museId} from '../scripts/lib/demo-data.mjs';

let db;const driver=randomUUID(),other=randomUUID(),trader=randomUUID(),foreignTrader=randomUUID(),admin=randomUUID();
before(async()=>{db=await createTestDatabase();for(const [id,role] of [[driver,'driver'],[other,'driver'],[trader,'trader'],[foreignTrader,'trader'],[admin,'admin']]) {await db.query('insert into auth.users(id,email) values($1,$2)',[id,`${id}@test.invalid`]);await db.query('update public.profiles set role=$1 where id=$2',[role,id]);}});
after(async()=>{await db?.close();});
function asUser(user,fn,role='authenticated') {return db.transaction(async tx=>{await tx.exec(`set local role ${role}`);await tx.query("select set_config('request.jwt.claim.sub',$1,true)",[user ?? '']);return fn(tx);});}
async function fresh(status='approved') {const id=randomUUID();await db.query("insert into public.shipments(id,trader_id,driver_id,origin,destination,cargo_type,cargo_description,quantity,pickup_date,route_gate_id,status) values($1,$2,$3,'Yangon','Muse','Textiles','Packed cargo',2,current_date+1,$4,$5)",[id,trader,driver,museId,status]);return id;}
async function row(id) {return (await db.query('select *,updated_at::text as revision from public.shipments where id=$1',[id])).rows[0];}
async function update(shipment,fields={},user=driver,role='authenticated') {const base={id:randomUUID(),revision:(await row(shipment)).revision,status:'picked_up',note:'Collected cargo',lat:16.84,lng:96.17,occurred:new Date().toISOString(),...fields};await asUser(user,tx=>tx.query('select public.append_driver_update($1,$2,$3,$4,$5,$6,$7,$8)',[base.id,shipment,base.revision,base.status,base.note,base.lat,base.lng,base.occurred]),role);return base;}
async function count(id) {return (await db.query('select count(*)::int as n from public.shipment_updates where shipment_id=$1',[id])).rows[0].n;}
function documentArgs(shipment,id=randomUUID()) {return {id,shipment,type:'photo',name:'cargo.png',mime:'image/png',size:32,ext:'png'};}
function path(args) {return `${args.shipment}/${driver}/${args.id}.${args.ext}`;}
async function store(args,user=driver) {return asUser(user,tx=>tx.query("insert into storage.objects(bucket_id,name,metadata) values('shipment-documents',$1,$2)",[path(args),JSON.stringify({mimetype:args.mime,size:args.size})]));}
async function register(args,user=driver) {return asUser(user,tx=>tx.query('select public.register_shipment_document($1,$2,$3,$4,$5,$6,$7)',[args.id,args.shipment,args.type,args.name,args.mime,args.size,args.ext]));}

test('only the assigned driver can update; anonymous, admin, trader and other driver are denied',async()=>{const id=await fresh();for(const user of [admin,trader,other]) await assert.rejects(update(id,{},user),{code:'42501'});await assert.rejects(update(id,{},null,'anon'),{code:'42501'});assert.equal(await count(id),0);});
test('status/GPS update commits atomically with server identity and synced history',async()=>{const id=await fresh();const input=await update(id);const shipment=await row(id);assert.equal(shipment.status,'picked_up');assert.equal(shipment.current_lat,input.lat);assert.equal(shipment.current_lng,input.lng);const event=(await db.query('select * from public.shipment_updates where id=$1',[input.id])).rows[0];assert.equal(event.actor_id,driver);assert.equal(event.driver_id,driver);assert.equal(event.sync_status,'synced');});
test('forward skips and same-state notes work, blank GPS preserves last position',async()=>{const id=await fresh();await update(id);await update(id,{status:'arrived_at_checkpoint',lat:null,lng:null});await update(id,{status:'arrived_at_checkpoint',note:'Waiting at checkpoint',lat:null,lng:null});assert.equal((await row(id)).current_lat,16.84);assert.equal(await count(id),3);});
test('unapproved, backward and delivered updates are rejected',async()=>{const pending=await fresh('requested');await assert.rejects(update(pending),{code:'PT422'});const id=await fresh();await update(id,{status:'in_transit'});await assert.rejects(update(id),{code:'PT422'});await update(id,{status:'delivered'});await assert.rejects(update(id,{status:'delivered'}),{code:'PT422'});assert.equal(await count(id),2);});
test('duplicate update retries are idempotent, conflicting IDs and stale updates fail',async()=>{const id=await fresh();const input=await update(id);await update(id,input);assert.equal(await count(id),1);await assert.rejects(update(id,{...input,note:'Different'}),{code:'PT409'});await assert.rejects(update(id,{revision:input.revision}),{code:'PT409'});await update(id,{status:'delivered'});await update(id,input);assert.equal((await row(id)).status,'delivered');assert.equal(await count(id),2);});
test('GPS, empty same-state changes and future timestamps are validated without partial writes',async()=>{const id=await fresh();for(const fields of [{lat:91},{lng:-181},{lat:null},{lat:NaN},{note:'x'.repeat(2001)},{occurred:'2999-01-01T00:00:00Z'},{status:'approved',note:'',lat:null,lng:null}]) await assert.rejects(update(id,fields),{code:'22023'});assert.equal(await count(id),0);assert.equal((await row(id)).status,'approved');});
test('old driver loses mutation/upload permission immediately after reassignment',async()=>{const id=await fresh();await db.query('update public.shipments set driver_id=$1 where id=$2',[other,id]);await assert.rejects(update(id),{code:'42501'});await assert.rejects(store(documentArgs(id)),{code:'42501'});});
test('evidence upload path requires current assigned driver and approved shipment',async()=>{const id=await fresh();const args=documentArgs(id);for(const user of [trader,other,admin]) await assert.rejects(store(args,user),{code:'42501'});await assert.rejects(store(documentArgs(await fresh('requested'))),{code:'42501'});await store(args);assert.equal((await asUser(other,tx=>tx.query('select name from storage.objects where name=$1',[path(args)]))).rows.length,0);});
test('document registration verifies real object metadata and rejects forged records',async()=>{const args=documentArgs(await fresh());await assert.rejects(register(args),{code:'PT422'});await store(args);for(const fields of [{size:33},{mime:'application/pdf'},{ext:'exe'},{size:10485761},{type:'executable'}]) await assert.rejects(register({...args,...fields}),{code:'22023'});await assert.rejects(register(args,other),{code:'42501'});await register(args);await register(args);assert.equal((await db.query('select count(*)::int as n from public.documents where id=$1',[args.id])).rows[0].n,1);});
test('registered evidence is visible only to authorized viewers and cannot be deleted by driver',async()=>{const args=documentArgs(await fresh());await store(args);await register(args);for(const user of [trader,admin,driver]) assert.equal((await asUser(user,tx=>tx.query('select name from storage.objects where name=$1',[path(args)]))).rows.length,1);for(const user of [other,foreignTrader]) assert.equal((await asUser(user,tx=>tx.query('select name from storage.objects where name=$1',[path(args)]))).rows.length,0);assert.equal((await asUser(driver,tx=>tx.query('delete from storage.objects where name=$1 returning name',[path(args)]))).rows.length,0);});
test('driver can clean only own unregistered uploads and attach delivery receipt after delivery',async()=>{const args=documentArgs(await fresh('delivered'));await store(args);assert.equal((await asUser(other,tx=>tx.query('delete from storage.objects where name=$1 returning name',[path(args)]))).rows.length,0);assert.equal((await asUser(driver,tx=>tx.query('delete from storage.objects where name=$1 returning name',[path(args)]))).rows.length,1);await store(args);await register({...args,type:'delivery_receipt'});});
