import Link from "next/link";
import {requireRole} from "@/lib/auth/session";
import {createClient} from "@/lib/supabase/server";
import {invitationsConfigured} from "@/lib/supabase/admin";
import {T} from "@/components/i18n/language-provider";
import {InviteDriverForm,ResendDriverInvite,DriverAccessForm} from "@/components/drivers/admin-driver-forms";
import {formatDate} from "@/lib/shipments/queries";

export default async function DriversPage({searchParams}:{searchParams:Promise<{page?:string}>}){
  await requireRole("admin");
  const params=await searchParams;const raw=Number(params.page??1);const page=Number.isSafeInteger(raw)&&raw>0&&raw<=10000?raw:1;
  const client=await createClient();const configured=invitationsConfigured();
  const [drivers,invitations]=await Promise.all([
    client.from("profiles").select("id,full_name,email,phone,driver_access",{count:"exact"}).eq("role","driver").order("created_at",{ascending:false}).order("id").range((page-1)*25,page*25-1),
    client.from("driver_invitations").select("id,full_name,email,status,last_sent_at,created_at").neq("status","accepted").order("created_at",{ascending:false}).order("id").limit(50),
  ]);
  return <><div className="page-heading"><div><p className="eyebrow"><T>OPERATIONS</T></p><h1><T>Drivers</T></h1><p className="muted"><T>Invite your team, review onboarding and manage Driver access.</T></p></div><Link href="/admin/shipments" className="button button-dark"><T>All shipments</T></Link></div><div className="driver-management-grid"><section className="panel"><InviteDriverForm configured={configured}/></section><section className="panel"><div className="panel-heading"><div><h2><T>Pending invitations</T></h2><p className="panel-subtitle"><T>Wait at least one minute between invitation attempts.</T></p></div></div>{invitations.error?<p role="alert" className="dashboard-message"><T>Could not load Drivers. Apply the onboarding migration and reload.</T></p>:!invitations.data?.length?<p className="dashboard-message"><T>No pending invitations.</T></p>:<ul className="driver-invitation-list">{invitations.data.map(invitation=><li key={invitation.id}><div><strong>{invitation.full_name}</strong><p>{invitation.email}</p><small><T>{invitation.status==='pending'?'Pending delivery':'Awaiting password setup'}</T> · {formatDate(invitation.last_sent_at??invitation.created_at,true)}</small></div><ResendDriverInvite id={invitation.id} configured={configured}/></li>)}</ul>}</section></div><section className="panel"><div className="panel-heading"><div><h2><T>Driver directory</T></h2><p className="panel-subtitle"><T>Only active Drivers who finish setup can receive assignments.</T></p></div></div>{drivers.error?<p role="alert" className="dashboard-message"><T>Could not load Drivers. Apply the onboarding migration and reload.</T></p>:!drivers.data?.length?<p className="dashboard-message"><T>No Drivers on this page.</T></p>:<div className="table-scroll"><table><thead><tr><th><T>Full name</T></th><th><T>Email address</T></th><th><T>Phone number</T></th><th><T>Access</T></th><th><T>Actions</T></th></tr></thead><tbody>{drivers.data.map(driver=><tr key={driver.id}><td>{driver.full_name}</td><td>{driver.email}</td><td>{driver.phone||'—'}</td><td><span className={'status-badge status-'+(driver.driver_access==='active'?'open':driver.driver_access==='disabled'?'closed':'delayed')}><T>{driver.driver_access==='active'?'Active':driver.driver_access==='disabled'?'Disabled':'Invited'}</T></span></td><td><DriverAccessForm id={driver.id} access={driver.driver_access}/></td></tr>)}</tbody></table></div>}<div className="table-footer"><span><T>Page</T> {page}</span><nav className="pagination" aria-label="Driver pages">{page>1&&<Link href={'/admin/drivers?page='+(page-1)}><T>← Previous</T></Link>}{page*25<(drivers.count??0)&&<Link href={'/admin/drivers?page='+(page+1)}><T>Next →</T></Link>}</nav></div></section></>;
}
