import {LanguageSwitch} from "@/components/i18n/language-switch";

import {T} from "@/components/i18n/language-provider";
import Link from "next/link";
import { Wordmark, RouteDrawing } from "@/components/brand/public-brand";

export default function HomePage() {
  return <div className="public-site">
    <a className="skip-link" href="#content"><T>Skip to content</T></a>
    <header className="site-header"><Wordmark /><nav aria-label="Main navigation"><LanguageSwitch/><a href="#how-it-works" className="desktop-nav"><T>How it works</T></a><a href="#routes" className="desktop-nav"><T>The routes</T></a><Link href="/login"><T>Log in</T></Link><Link href="/signup" className="ink-button small-button"><T>Get started </T><span aria-hidden="true">↗</span></Link></nav></header>
    <main id="content">
      <section className="landing-hero">
        <div className="hero-copy"><p className="editorial-label"><span className="rust-rule" /><T> BUILT AROUND MYANMAR’S TRADE</T></p><h1><T>Every shipment.</T><br /><T>A clearer </T><em><T>journey.</T></em></h1><p className="hero-description"><T>From a warehouse in Yangon to a checkpoint in Muse. Keep your cargo, your drivers and your next decision on the same page.</T></p><div className="hero-actions"><Link href="/signup" className="ink-button"><T>Start your first shipment </T><span aria-hidden="true">↗</span></Link><a href="#how-it-works" className="underlined-link"><T>Take a closer look </T><span aria-hidden="true">↓</span></a></div><p className="hero-footnote"><T>One shared view for traders, drivers and operations.</T></p></div>
        <figure className="journey-print"><div className="print-heading"><span><T>FIELD NOTES / 01</T></span><span><T>MYANMAR CORRIDORS</T></span></div><RouteDrawing /><figcaption><span><T>A country connected by journeys.</T></span><span><T>Illustrated routes · Not live conditions</T></span></figcaption></figure>
      </section>
      <div className="capability-strip" aria-label="Shipment tools"><span><T>Shipment tracking</T></span><span><T>Border gate alerts</T></span><span><T>Driver updates</T></span><span><T>Delivery documents</T></span></div>
      <section id="how-it-works" className="editorial-section workflow-section"><div className="section-intro"><p className="editorial-label"><T>01 / FROM REQUEST TO ARRIVAL</T></p><h2><T>Less chasing updates.</T><br /><em><T>More knowing.</T></em></h2><p><T>Moving goods takes coordination. Keep the details together, so everyone can see what happened and what comes next.</T></p></div><ol className="workflow-list">{[
        ["Make the request.","Tell operations what you’re moving, where it’s going and when it needs to leave. Your shipment starts with a clear record."],
        ["Follow the road.","Operations assigns a driver. Each saved status and location update appears on your shipment timeline and map."],
        ["Stay ahead of a change.","When operations reports a gate delay or closure, affected traders receive an alert. Photos and paperwork stay with the shipment."],
      ].map(([title,description],index)=><li key={title}><span className="step-number">0{index+1}</span><div><h3>{title}</h3><p>{description}</p></div><span className="step-arrow" aria-hidden="true">↗</span></li>)}</ol></section>
      <section id="routes" className="corridor-section"><div className="corridor-heading"><p className="editorial-label"><T>02 / THE ROUTES WE WORK AROUND</T></p><h2><T>Local routes.</T><br /><em><T>Shared visibility.</T></em></h2><p><T>Built for the handoffs between Myanmar’s trading hubs and border gates.</T></p></div><div className="corridor-list"><article><span className="route-index"><T>NORTHERN CORRIDOR</T></span><h3><T>Yangon </T><span aria-hidden="true">↗</span><T> Muse</T></h3><p><T>Through Mandalay, towards the China border.</T></p><div className="route-stops"><span><T>Yangon</T></span><i /><span><T>Mandalay</T></span><i /><span><T>Muse</T></span></div></article><article><span className="route-index"><T>EASTERN CORRIDOR</T></span><h3><T>Yangon </T><span aria-hidden="true">↗</span><T> Myawaddy</T></h3><p><T>From the commercial hub towards the Thailand border.</T></p><div className="route-stops"><span><T>Yangon</T></span><i /><span><T>Myawaddy</T></span></div></article><p className="corridor-note"><T>Route conditions are reported by your operations team. Check the latest gate status inside your workspace.</T></p></div></section>
      <section className="editorial-section people-section"><div className="section-intro"><p className="editorial-label"><T>03 / EVERYONE HAS THEIR PART</T></p><h2><T>One journey.</T><br /><em><T>Three perspectives.</T></em></h2></div><div className="people-list"><article><span><T>FOR TRADERS</T></span><h3><T>Your cargo, in view.</T></h3><p><T>Request transport, follow progress and find your shipment documents in one place.</T></p><Link href="/signup" className="underlined-link"><T>Create a Trader account ↗</T></Link></article><article><span><T>FOR OPERATIONS</T></span><h3><T>A coordinated day.</T></h3><p><T>Review requests, assign drivers and share gate conditions with the people affected.</T></p></article><article><span><T>FOR DRIVERS</T></span><h3><T>Keep the team posted.</T></h3><p><T>Share a status, capture your location and attach evidence from your phone. Queue updates from an open page when offline.</T></p></article></div></section>
      <section className="closing-section"><p className="editorial-label"><T>THE NEXT JOURNEY STARTS HERE</T></p><h2><T>Let’s get your cargo</T><br /><em><T>on the same page.</T></em></h2><Link href="/signup" className="ink-button"><T>Create your account </T><span aria-hidden="true">↗</span></Link><p><T>Already part of the team? </T><Link href="/login"><T>Log in</T></Link></p></section>
    </main>
    <footer className="site-footer"><Wordmark /><p><T>Made for the journeys that connect Myanmar.</T></p><div><Link href="/login"><T>Log in</T></Link><Link href="/signup"><T>Sign up</T></Link><a href="#content"><T>Back to top ↑</T></a></div></footer>
  </div>;
}
